name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Run tests
        run: go test ./...

      - name: Create bin directory
        run: mkdir -p bin

      - name: Build binary
        run: go build -o bin/painter-app ./cmd/painter
